### ISSUE TITLE
RAM usage in SCISSOR_TCGA

### ISSUE THREAD

**Issue by Mengflz** [icbi-lab/luca#16]
Hi, thank you for your work. When I was performing SCISSOR_TCGA step, I encountered an issue requiring over three thousand GB RAM. I wanted to inquire about how much memory resources you used when performing SCISSOR_TCGA?

**Comment by grst** [comment]
I was working on a system where memory wasn't that much of an issue, so I can't say exactly, but I think you should be good with ~30 GB *per process*. Since there will be several hundred scissor processes be lauched at the same time, 3000GB doesn't sound too unrealistic. 

If you have memory issues, I recommend adding
```nextflow
memory = 30.GB
```
to the process configuration here: 
https://github.com/icbi-lab/luca/blob/5ffb0a4671e9c288b10e73de18d447ee176bef1d/conf/downstream_analyses.config#L165-L173

Then nextflow should take care of not launching more processes simultaneously than there's memory available.

**Comment by Mengflz** [comment]
Thank you for your response. I found that the problem might be due to my incorrect usage of the data.
